on:
  workflow_dispatch:
    inputs:
      dry:
        description: 'Dry run'
        required: true
        type: boolean
      all:
        description: 'Update all'
        required: true
        type: boolean
  schedule:
    - cron: '0 3 * * 0'

jobs:
  Build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: NixOS/patchelf
        path: patchelf
        ref: 0.13.1

    - name: Compile
      run: |
        PRE_CMD=""
        if [[ "${{ matrix.arch }}" == "i686" ]]; then
          PRE_CMD="linux32"
        fi
        SCRIPT=$(cat <<-END
          ${PRE_CMD}
          set -ex
          cd /pwd/patchelf
          ./bootstrap.sh
          ./configure --prefix="/pwd/AppDir/usr"
          make
          make install
          strip "/pwd/AppDir/usr/bin/patchelf"
        END
        )
        docker run --mount type=bind,source=$(pwd),target=/pwd                 \
                   quay.io/pypa/manylinux_2_28 /bin/bash -c     \
                   "${SCRIPT}"

    - name: Package
      run: |
        apt update && apt install libfuse2 -y
        wget -cq https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-${{ matrix.arch }}.AppImage
        chmod u+x appimagetool-${{ matrix.arch }}.AppImage
        ln -s patchelf.png AppDir/.DirIcon
        ln -s usr/bin/patchelf AppDir/AppRun
        if [[ ${{ matrix.arch }} == "i686" ]]; then
          SCRIPT=$(cat <<-END
            linux32
            apt-get update
            apt-get install -y file
            set -ex
            trap 'rm -rf /pwd/squashfs-root' EXIT
            cd /pwd
            ./appimagetool-i686.AppImage --appimage-extract &> /dev/null
            ./squashfs-root/AppRun AppDir
        END
          )
          docker run --mount type=bind,source=$(pwd),target=/pwd               \
                     i686/ubuntu /bin/bash -c "${SCRIPT}"
        else
          ./appimagetool-${{ matrix.arch }}.AppImage AppDir
        fi
        echo "PATCHELF_APPIMAGE=$(ls patchelf-*.AppImage)" >> $GITHUB_ENV

